# Copyright 2023, Pluto VR, Inc.
#
# SPDX-License-Identifier: BSL-1.0

set(GST_LIBRARIES
    ${GST_ARCH_DIR}/lib/libgstreamer-1.0.so
    ${GST_ARCH_DIR}/lib/libgstrtsp-1.0.so
    # ${GST_ARCH_DIR}/lib/libgstphotography-1.0.so
    # ${GST_ARCH_DIR}/lib/liboggkate.so
    # ${GST_ARCH_DIR}/lib/libx264.so
    # ${GST_ARCH_DIR}/lib/libspeex.so
    # ${GST_ARCH_DIR}/lib/libtheoradec.so
    # ${GST_ARCH_DIR}/lib/libgstaudio-1.0.so
    # ${GST_ARCH_DIR}/lib/libgstfft-1.0.so
    # ${GST_ARCH_DIR}/lib/libpcre2-8.so
    # ${GST_ARCH_DIR}/lib/libtheoraenc.so
    # ${GST_ARCH_DIR}/lib/libgsttranscoder-1.0.so
    # ${GST_ARCH_DIR}/lib/libiconv.so
    ${GST_ARCH_DIR}/lib/libintl.so
    # ${GST_ARCH_DIR}/lib/libgstbadaudio-1.0.so
    # ${GST_ARCH_DIR}/lib/libssl.so
    # ${GST_ARCH_DIR}/lib/libgstwebrtcnice-1.0.so
    # ${GST_ARCH_DIR}/lib/libopenjp2.so
    # ${GST_ARCH_DIR}/lib/libfreetype.so
    # ${GST_ARCH_DIR}/lib/libgstcodecparsers-1.0.so
    # ${GST_ARCH_DIR}/lib/libzbar.so
    # ${GST_ARCH_DIR}/lib/liborc-test-0.4.so
    # ${GST_ARCH_DIR}/lib/libpangocairo-1.0.so
    # ${GST_ARCH_DIR}/lib/libgstvalidate-1.0.so
    # ${GST_ARCH_DIR}/lib/libffi.so
    # ${GST_ARCH_DIR}/lib/libgstvideo-1.0.so
    # ${GST_ARCH_DIR}/lib/libavformat.so
    # ${GST_ARCH_DIR}/lib/libgstrtp-1.0.so
    # ${GST_ARCH_DIR}/lib/libgsturidownloader-1.0.so
    # ${GST_ARCH_DIR}/lib/libwavpack.so
    # ${GST_ARCH_DIR}/lib/libvorbis.so
    # ${GST_ARCH_DIR}/lib/libgstapp-1.0.so
    # ${GST_ARCH_DIR}/lib/libopus.so
    # ${GST_ARCH_DIR}/lib/libglib-2.0.so
    # ${GST_ARCH_DIR}/lib/libgstinsertbin-1.0.so
    # ${GST_ARCH_DIR}/lib/libcairo.so
    # ${GST_ARCH_DIR}/lib/libgstisoff-1.0.so
    # ${GST_ARCH_DIR}/lib/libgstsctp-1.0.so
    # ${GST_ARCH_DIR}/lib/libkate.so
    # ${GST_ARCH_DIR}/lib/libdca.so
    # ${GST_ARCH_DIR}/lib/libopenh264.so
    # ${GST_ARCH_DIR}/lib/librtmp.so
    # ${GST_ARCH_DIR}/lib/libpng16.so
    # ${GST_ARCH_DIR}/lib/libfontconfig.so
    # ${GST_ARCH_DIR}/lib/libgstvulkan-1.0.so
    # ${GST_ARCH_DIR}/lib/libvorbisfile.so
    # ${GST_ARCH_DIR}/lib/libgstmpegts-1.0.so
    # ${GST_ARCH_DIR}/lib/libtheora.so
    # ${GST_ARCH_DIR}/lib/libdav1d.so
    # ${GST_ARCH_DIR}/lib/libpangoft2-1.0.so
    # ${GST_ARCH_DIR}/lib/libgstsdp-1.0.so
    # ${GST_ARCH_DIR}/lib/libgstnet-1.0.so
    # ${GST_ARCH_DIR}/lib/libopencore-amrwb.so
    # ${GST_ARCH_DIR}/lib/libharfbuzz.so
    # ${GST_ARCH_DIR}/lib/libcrypto.so
    # ${GST_ARCH_DIR}/lib/libmp3lame.so
    # ${GST_ARCH_DIR}/lib/libspandsp.so
    ${GST_ARCH_DIR}/lib/libgmodule-2.0.so
    # ${GST_ARCH_DIR}/lib/libbz2.so
    # ${GST_ARCH_DIR}/lib/libcroco-0.6.so
    # ${GST_ARCH_DIR}/lib/libjson-glib-1.0.so
    # ${GST_ARCH_DIR}/lib/libgstriff-1.0.so
    # ${GST_ARCH_DIR}/lib/libgstplayer-1.0.so
    # ${GST_ARCH_DIR}/lib/libgstcodecs-1.0.so
    # ${GST_ARCH_DIR}/lib/libges-1.0.so
    # ${GST_ARCH_DIR}/lib/libwebrtc_audio_processing.so
    # ${GST_ARCH_DIR}/lib/libavcodec.so
    # ${GST_ARCH_DIR}/lib/libjpeg.so
    # ${GST_ARCH_DIR}/lib/libxml2.so
    # ${GST_ARCH_DIR}/lib/libpango-1.0.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstrsvg.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstudp.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstproxy.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstsdpelem.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstid3demux.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstclosedcaption.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstdvdsub.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstdvbsuboverlay.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstopusparse.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaudiomixmatrix.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstflv.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstadpcmenc.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvideofiltersbad.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstrtpmanager.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstgoom.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaudioparsers.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvideorate.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvideofilter.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstwavpack.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvulkan.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgsty4mdec.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstsrtp.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaiff.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstsubenc.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstapetag.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaes.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvideoframe_audiolevel.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaudioconvert.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstbayer.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgsticydemux.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstfrei0r.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstjpegformat.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaudiobuffersplit.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstrtpmanagerbad.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstadpcmdec.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstmpegpsdemux.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstnle.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstbz2.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaudiofx.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaudiorate.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvideotestsrc.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstogg.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstfieldanalysis.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvideobox.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstwavenc.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstadaptivedemux2.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstrealmedia.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstopenh264.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstcoreelements.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgsthls.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstwavparse.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstrist.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstxingmux.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstdtsdec.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstsoup.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstauparse.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvolume.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgsttheora.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstkate.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstrtsp.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstencoding.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstsmoothstreaming.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstpango.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstid3tag.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaudiolatency.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstsegmentclip.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstcoloreffects.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstspeed.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstmpg123.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstrtspclientsink.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstsoundtouch.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstadder.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgsttypefindfunctions.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstautoconvert.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstplayback.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaudioresample.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstasfmux.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaudiofxbad.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstopus.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgsttaglib.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstmpegtsmux.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgsta52dec.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstwebrtc.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstmultipart.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstdeinterlace.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstsmpte.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgsty4menc.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstnetsim.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstgeometrictransform.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstrtmp.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstopenjpeg.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstcodectimestamper.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvideocrop.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstdebugutilsbad.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstcoretracers.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstassrender.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstzbar.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstladspa.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaudiovisualizers.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstx264.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstalphacolor.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstlibav.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstremovesilence.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstges.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstgio.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstlevel.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstgdp.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstalpha.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstautodetect.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstinterleave.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvorbis.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstimagefreeze.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstmxf.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvideoconvertscale.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstspeex.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstopengl.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstjpeg.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstshapewipe.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstalaw.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstspandsp.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstdvdlpcmdec.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstmultifile.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstdv.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstreplaygain.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstcamerabin.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstipcpipeline.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstinterlace.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstrfbsrc.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstcutter.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstsrt.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstrtmp2.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstmidi.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstmulaw.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstdebug.so
    ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstandroidmedia.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstlame.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstmatroska.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstcairo.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstgaudieffects.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstpnm.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstmpegtsdemux.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstsctp.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstoverlaycomposition.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstflac.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstdtls.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstwebrtcdsp.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstpcapparse.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgsttimecode.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgsteffectv.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstnice.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstsiren.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstmpegpsmux.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaudiomixer.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstdvdspu.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstspectrum.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstrawparse.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvideoparsersbad.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstcompositor.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstisomp4.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstinter.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstgdkpixbuf.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstequalizer.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstlegacyrawparse.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstdtmf.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstpng.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstsmooth.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvpx.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstivtc.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstasf.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstsbc.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstdash.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvideomixer.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgsttcp.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstapp.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaccurip.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstopensles.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstgoom2k1.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstfreeverb.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstrtp.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstsubparse.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstaudiotestsrc.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstflxdec.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstvoaacenc.so
    # ${GST_ARCH_DIR}/lib/gstreamer-1.0/libgstavi.so
    # ${GST_ARCH_DIR}/lib/libfribidi.so
    # ${GST_ARCH_DIR}/lib/libgraphene-1.0.so
    # ${GST_ARCH_DIR}/lib/libgstwebrtc-1.0.so
    # ${GST_ARCH_DIR}/lib/libcairo-gobject.so
    # ${GST_ARCH_DIR}/lib/liborc-0.4.so
    # ${GST_ARCH_DIR}/lib/librsvg-2.so
    # ${GST_ARCH_DIR}/lib/libSoundTouch.so
    # ${GST_ARCH_DIR}/lib/libsqlite3.so
    # ${GST_ARCH_DIR}/lib/libsrtp2.so
    # ${GST_ARCH_DIR}/lib/libgstgl-1.0.so
    # ${GST_ARCH_DIR}/lib/liba52.so
    # ${GST_ARCH_DIR}/lib/libvorbisenc.so
    # ${GST_ARCH_DIR}/lib/libgstpbutils-1.0.so
    # ${GST_ARCH_DIR}/lib/libcairo-script-interpreter.so
    ${GST_ARCH_DIR}/lib/libgobject-2.0.so
    ${GST_ARCH_DIR}/lib/libpixman-1.so
    # ${GST_ARCH_DIR}/lib/libdv.so
    # ${GST_ARCH_DIR}/lib/libogg.so
    # ${GST_ARCH_DIR}/lib/libtiff.so
    # ${GST_ARCH_DIR}/lib/libtag.so
    # ${GST_ARCH_DIR}/lib/libsrt.so
    ${GST_ARCH_DIR}/lib/libnice.so
    # ${GST_ARCH_DIR}/lib/libgstplay-1.0.so
    ${GST_ARCH_DIR}/lib/libgstallocators-1.0.so
    # ${GST_ARCH_DIR}/lib/gio/modules/libgioopenssl.so
    # ${GST_ARCH_DIR}/lib/libgdk_pixbuf-2.0.so
    # ${GST_ARCH_DIR}/lib/libgstbasecamerabinsrc-1.0.so
    # ${GST_ARCH_DIR}/lib/libmpg123.so
    # ${GST_ARCH_DIR}/lib/libswresample.so
    ${GST_ARCH_DIR}/lib/libz.so
    ${GST_ARCH_DIR}/lib/libsoup-2.4.so
    ${GST_ARCH_DIR}/lib/libFLAC.so
    ${GST_ARCH_DIR}/lib/libgio-2.0.so
    # ${GST_ARCH_DIR}/lib/libexpat.so
    # ${GST_ARCH_DIR}/lib/libvpx.so
    # ${GST_ARCH_DIR}/lib/libavutil.so
    # ${GST_ARCH_DIR}/lib/libgstadaptivedemux-1.0.so
    # ${GST_ARCH_DIR}/lib/libvo-aacenc.so
    # ${GST_ARCH_DIR}/lib/libsbc.so
    # ${GST_ARCH_DIR}/lib/libgstrtspserver-1.0.so
    # ${GST_ARCH_DIR}/lib/libgsttag-1.0.so
    # ${GST_ARCH_DIR}/lib/libpsl.so
    # ${GST_ARCH_DIR}/lib/libass.so
    ${GST_ARCH_DIR}/lib/libgthread-2.0.so
    # ${GST_ARCH_DIR}/lib/libcharset.so
    ${GST_ARCH_DIR}/lib/libgstbase-1.0.so
    # ${GST_ARCH_DIR}/lib/libgstcheck-1.0.so
    # ${GST_ARCH_DIR}/lib/libavfilter.so
    # ${GST_ARCH_DIR}/lib/libgstcontroller-1.0.so
    # ${GST_ARCH_DIR}/lib/libturbojpeg.so
	)

set(JSONGLIB_LIBRARIES ${GST_ARCH_DIR}/lib/libjson-glib-1.0.so)
